/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sponsors".
 */
export interface Sponsors {
  id: string;
  tiers?: {
    name: string;
    logoHeight: number;
    sponsors?: {
      url: string;
      logo: string | Media;
      id?: string;
    }[];
    id?: string;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_groups".
 */
export interface TeamGroups {
  id: string;
  groups?: {
    name: string;
    urlName: string;
    teams: {
      team: string | Team;
      id?: string;
    }[];
    id?: string;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: string;
  name: string;
  urlName: string;
  shortDescription?: string;
  description?: {
    [k: string]: unknown;
  }[];
  coverImage?: string | Media;
  members?: {
    user: string | User;
    title?: string;
    allowEdit?: boolean;
    id?: string;
  }[];
  projects?: {
    name: string;
    start: string;
    end: string;
    id?: string;
  }[];
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  name: string;
  profilePhoto?: string | Media;
  admin?: boolean;
  bio?: {
    [k: string]: unknown;
  }[];
  linkedin?: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  content: {
    [k: string]: unknown;
  }[];
  authors?: {
    user: string | User;
    id?: string;
  }[];
}
