name: ci

on:
  push:
    branches:
      - 'far-future'

jobs:
  cms-server:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      -
        id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1094350379976/locations/global/workloadIdentityPools/pool/providers/github-provider'
          service_account: 'ci-account@macrocketry.iam.gserviceaccount.com'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      -
        name: Build and upload docker image for cms
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gcr.io/macrocketry/cms:latest
          build-args: PAYLOAD_PUBLIC_SERVER_URL=https://next-macrocketry-ca.vercel.app
          file: apps/cms/Dockerfile
      -
        name: Deploy cms on cloud run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: cms
          image: gcr.io/macrocketry/cms